services:
  mysql:
    image: mysql:${MYSQL_IMAGE_TAG}
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_USER_FILE: /run/secrets/mysql-user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - db-network
    secrets:
      - mysql-root-password
      - mysql-user
      - mysql-password

secrets:
  mysql-root-password:
    file: secrets/mysql-root-password.txt
  mysql-user:
    file: secrets/mysql-user.txt
  mysql-password:
    file: secrets/mysql-password.txt

networks:
  db-network:
    driver: bridge
